# Generated by Django 3.1.1 on 2021-04-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0005_auto_20210401_2227'),
        ('Patient', '0004_auto_20210329_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Schedule.schedule')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
