# Generated by Django 3.1.1 on 2021-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
