# Generated by Django 3.1.1 on 2021-04-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
