# Generated by Django 3.1.1 on 2021-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('favicon', models.ImageField(upload_to='global/favicon')),
                ('logo', models.ImageField(upload_to='global/logo')),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('footer_text', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=300)),
                ('twitter_url', models.CharField(max_length=300)),
                ('youtube_url', models.CharField(max_length=300)),
                ('instagram_url', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
