# Generated by Django 3.1.1 on 2021-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='contact',
            field=models.CharField(default='+91 9234568463', max_length=13),
        ),
        migrations.AlterField(
            model_name='global',
            name='hospital',
            field=models.CharField(default='Genetic', max_length=60),
        ),
        migrations.AlterField(
            model_name='global',
            name='visible',
            field=models.CharField(default='HMS', max_length=10),
        ),
    ]
