# Generated by Django 3.1.1 on 2021-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_auto_20210402_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
