# Generated by Django 3.1.1 on 2021-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fees',
            field=models.IntegerField(max_length=20),
        ),
    ]
