# Generated by Django 3.1.1 on 2021-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_auto_20210401_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
