# Generated by Django 3.1.1 on 2021-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(blank=True, max_length=10)),
                ('mobile_no', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('blood_pressure', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('address', models.TextField()),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_mobile_no', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
