# Generated by Django 3.1.1 on 2021-03-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20210327_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='guardian_mobile_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relationship',
        ),
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.category'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(max_length=7),
        ),
    ]
